-- MySQL Script generated by MySQL Workbench
-- Wed Oct  5 14:48:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE TABLE IF NOT EXISTS `admin` (
  `idadmin` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `senha` INT NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `raca` (
  `idraca` INT NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`idraca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `animal` (
  `idanimal` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `imagem` VARCHAR(45) NULL,
  `desc` VARCHAR(45) NULL,
  `disp_adocao` VARCHAR(45) NULL,
  `tipoAnimal` VARCHAR(45) NULL,
  `admin_idadmin` INT NOT NULL,
  `raca_idraca` INT NOT NULL,
  PRIMARY KEY (`idanimal`, `admin_idadmin`, `raca_idraca`),
  INDEX `fk_animal_admin_idx` (`admin_idadmin` ASC),
  INDEX `fk_animal_raca1_idx` (`raca_idraca` ASC),
  CONSTRAINT `fk_animal_admin`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_raca1`
    FOREIGN KEY (`raca_idraca`)
    REFERENCES `raca` (`idraca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
